### ISSUE TITLE
[CY-5830] How to actually convert gosec results?

### ISSUE THREAD

**Issue by soulshake** [codacy/codacy-gosec#20]
First, thanks for building Codacy, it's great!

The reason for this issue is that it's unclear how to convert the output of `gosec` into a format supported by Codacy.

[`README.md`](https://github.com/codacy/codacy-gosec#sending-the-results-to-codacy) says: 

> ### Sending the results to Codacy
> Sending the results of running gosec to Codacy involves the steps below, which you can automate in your CI build process:
> 
> 1. Run gosec
> 2. Convert the gosec output to a format that the Codacy API accepts
> ...

The following example includes this snippet:

```
gosec -fmt json -log log.txt ./... | ./codacy-gosec-"<version>"
```

But I can't find a file like that in this repo, and running the build instructions doesn't seem to generate it either.
Where is this `./codacy-gosec-"<version>"` file supposed to come from?

**Comment by lolgab** [comment]
You can download it from the Github releases page: https://github.com/codacy/codacy-gosec/releases/tag/0.3.7
It is distributed as a linux binary ([codacy-gosec-0.3.7](https://github.com/codacy/codacy-gosec/releases/download/0.3.7/codacy-gosec-0.3.7)) and as a Java jar ([codacy-gosec-0.3.7.jar](https://github.com/codacy/codacy-gosec/releases/download/0.3.7/codacy-gosec-0.3.7.jar)) for non-linux environments.

**Comment by soulshake** [comment]
Omg. :facepalm: Thank you!
